# Generated by Django 2.0.6 on 2019-10-30 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191025_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='productImage'),
            preserve_default=False,
        ),
    ]
